// <auto-generated />
using System;
using CalendarAppointmentApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarAppointmentApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430041800_FixDb")]
    partial class FixDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalendarAppointmentApp.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.GroupMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GroupMeetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprint Planning",
                            StartTime = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.GroupMeetingParticipant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupMeetingId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupMeetingId");

                    b.HasIndex("GroupMeetingId");

                    b.ToTable("GroupMeetingParticipants");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MinutesBefore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nguyên Khang",
                            Password = "123",
                            Username = "khang"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xuân Mạnh",
                            Password = "123",
                            Username = "manh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quốc Trung",
                            Password = "123",
                            Username = "trung"
                        });
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Appointment", b =>
                {
                    b.HasOne("CalendarAppointmentApp.Models.Calendar", "Calendar")
                        .WithMany("Appointments")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Calendar", b =>
                {
                    b.HasOne("CalendarAppointmentApp.Models.User", "User")
                        .WithOne("Calendar")
                        .HasForeignKey("CalendarAppointmentApp.Models.Calendar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.GroupMeetingParticipant", b =>
                {
                    b.HasOne("CalendarAppointmentApp.Models.GroupMeeting", "GroupMeeting")
                        .WithMany("Participants")
                        .HasForeignKey("GroupMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarAppointmentApp.Models.User", "User")
                        .WithMany("GroupMeetingParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMeeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Reminder", b =>
                {
                    b.HasOne("CalendarAppointmentApp.Models.Appointment", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Appointment", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.Calendar", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.GroupMeeting", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CalendarAppointmentApp.Models.User", b =>
                {
                    b.Navigation("Calendar");

                    b.Navigation("GroupMeetingParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
